services:
  - type: web
    name: partner-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: Backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Add these in Render dashboard:
      # - FIREBASE_PROJECT_ID
      # - FIREBASE_PRIVATE_KEY
      # - FIREBASE_CLIENT_EMAIL
      # - EMAIL_USER
      # - EMAIL_PASS
      # - FRONTEND_URL
    healthCheckPath: /
